Repository paketo-buildpacks/packit, pull requests merged in 2022-08, with the labels that each got.

#365 Validate env var names before writing env var files
  internal/environment_writer.go
  internal/environment_writer_test.go
Labels: semver:patch

#369 Makes CycloneDX SBOM Reproducible
  sbom/formatted_reader.go
  sbom/formatted_reader_test.go
  sbom/sbom_outputs_test.go
Labels: semver:minor

#371 Adds a reproducibility verification check
  sbom/formatted_reader_test.go
Labels: semver:patch

#376 Add support for wild-card stacks in dependencies
  postal/buildpack.go
  postal/service_test.go
Labels: semver:minor

#373 GenerateFromDependency without CPE or PURL
  sbom/sbom.go
  sbom/sbom_test.go
Labels: semver:minor

#380 Update lint.yml
  .github/workflows/lint.yml
  sbom/sbom.go
Labels: semver:patch

#379 Marshal CycloneDX/SPDX SBOM with indentation
  sbom/formatted_reader.go
  sbom/formatted_reader_test.go
  sbom/sbom.go
Labels: enhancement, semver:patch

#382 Adds strip-components field to cargo
  cargo/config.go
  cargo/config_test.go
Labels: semver:patch

#385 Standardize workflows to appear more similar to github-config
  .github/.patch_files
  .github/.syncignore
  .github/dependabot.yml
  .github/labels.yml
  .github/workflows/approve-bot-pr.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-draft-release.yml
  .github/workflows/label-pr.yml
  .github/workflows/lint-yaml.yml
  .github/workflows/lint.yml
  .github/workflows/synchronize-labels.yml
  .github/workflows/test-pull-request.yml
Labels: semver:patch
